### ISSUE TITLE
Request: Touch Input

### ISSUE THREAD

**Issue by siberiansun** [gumilastik/VVVV.HTMLTexture.DX11#2]
Would be really nice if HTML Texture could handle touch input for scrolling content.

**Comment by gumilastik** [comment]
Currently CEF does not support (multitouch)touch input. There is some patch for CEF that allow to do it, but ChromiumFX generated from original sources (without any patches). So you can only emulate scrolling behavior through js execution:
`window.scrollTo(X, Y);`

**Comment by simonemarin** [comment]
Curious, it does work with window.scrollTo(x,y); but it doesn t with $('.myclass´).scrollTo(x,y); any idea why? 
of course
.myclass { height: 300px; overflow: auto;}
Simone

**Comment by gumilastik** [comment]
This question more related to JS. As I remember only window object can use scrollTo method, DOM object may use scrollTop and scrollLeft properties instead.
With jQuery you can use:

```
$('.myclass').scrollLeft(X).scrollTop(Y);
```

Or some scrolling plugins like [ScrollTo](http://balupton.github.io/jquery-scrollto/).
