### ISSUE TITLE
On screen keyboard

### ISSUE THREAD

**Issue by simonemarin** [gumilastik/VVVV.HTMLTexture.DX11#3]
Hi, how to trigger an on screen keyboard upon clicking in an input field?
tx
Simone

**Comment by gumilastik** [comment]
See "Injecting jQuery" help patch. It monitors activation/deactivation of any input field on the page.

**Comment by simonemarin** [comment]
Hi, yes thanks I had already found that out using something like

```
    $(".form-control").mouseup(function() {
      //  alert("hello click");
        if ("vvvv" in window) vvvv.hello(0);
    });

    $(".form-control").mousedown(function() {
      //  alert("hello click");
        if ("vvvv" in window) vvvv.hello(1);
    });
```

I am then using a custom keyboard, as the Windows OSK exposed a link to the control panel, that could me mitigated fiddling with the GPO but it was a better solution to use a third party keyboard such as http://chessware.ch/virtual-keyboard/. We could even do a vvvv based keyboard.
S.

**Comment by simonemarin** [comment]
I ended up using a native jquery keyboard, it seems to be more natural to let the HTML node to take care internally of everything instead of having to externalize services.
